using OptimumERP.AI.Models;

namespace OptimumERP.AI.TrainingData
{
    public static class ClassificationTrainingData
    {
        public static List<ColumnNameData> GetData = new List<ColumnNameData>
        {
            // ================= ITEM =================
            new ColumnNameData { ColumnText = "Item", Label = "Item" },
            new ColumnNameData { ColumnText = "Items", Label = "Item" },
            new ColumnNameData { ColumnText = "Product", Label = "Item" },
            new ColumnNameData { ColumnText = "Product Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Article", Label = "Item" },
            new ColumnNameData { ColumnText = "Material", Label = "Item" },
            new ColumnNameData { ColumnText = "Goods", Label = "Item" },
            new ColumnNameData { ColumnText = "SKU", Label = "Item" },
            new ColumnNameData { ColumnText = "Barcode", Label = "Item" },
            new ColumnNameData { ColumnText = "Part Number", Label = "Item" },
            new ColumnNameData { ColumnText = "Item Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Item Description", Label = "Item" },
            new ColumnNameData { ColumnText = "Product ID", Label = "Item" },
            new ColumnNameData { ColumnText = "Product Title", Label = "Item" },
            new ColumnNameData { ColumnText = "Prod", Label = "Item" },
            new ColumnNameData { ColumnText = "Prod Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Stock Keeping Unit", Label = "Item" },
            new ColumnNameData { ColumnText = "Inventory Item", Label = "Item" },
            new ColumnNameData { ColumnText = "Catalog Item", Label = "Item" },
            new ColumnNameData { ColumnText = "Merchandise", Label = "Item" },
            new ColumnNameData { ColumnText = "Merch", Label = "Item" },
            new ColumnNameData { ColumnText = "Stock", Label = "Item" },
            new ColumnNameData { ColumnText = "Stock Number", Label = "Item" },
            new ColumnNameData { ColumnText = "Stock ID", Label = "Item" },
            new ColumnNameData { ColumnText = "Material Number", Label = "Item" },
            new ColumnNameData { ColumnText = "Mat No", Label = "Item" },
            new ColumnNameData { ColumnText = "Part", Label = "Item" },
            new ColumnNameData { ColumnText = "Part ID", Label = "Item" },
            new ColumnNameData { ColumnText = "Component", Label = "Item" },
            new ColumnNameData { ColumnText = "Component Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Component No", Label = "Item" },
            new ColumnNameData { ColumnText = "Line Item", Label = "Item" },
            new ColumnNameData { ColumnText = "Order Item", Label = "Item" },
            new ColumnNameData { ColumnText = "Order Line", Label = "Item" },
            new ColumnNameData { ColumnText = "Order Description", Label = "Item" },
            new ColumnNameData { ColumnText = "Description", Label = "Item" },
            new ColumnNameData { ColumnText = "Desc", Label = "Item" },
            new ColumnNameData { ColumnText = "Prod Desc", Label = "Item" },
            new ColumnNameData { ColumnText = "Product Description", Label = "Item" },
            new ColumnNameData { ColumnText = "Item Desc", Label = "Item" },
            new ColumnNameData { ColumnText = "Article Number", Label = "Item" },
            new ColumnNameData { ColumnText = "Article ID", Label = "Item" },
            new ColumnNameData { ColumnText = "Goods Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Goods No", Label = "Item" },
            new ColumnNameData { ColumnText = "UPC", Label = "Item" },
            new ColumnNameData { ColumnText = "EAN", Label = "Item" },
            new ColumnNameData { ColumnText = "GTIN", Label = "Item" },
            new ColumnNameData { ColumnText = "Model", Label = "Item" },
            new ColumnNameData { ColumnText = "Model Number", Label = "Item" },
            new ColumnNameData { ColumnText = "Model No", Label = "Item" },
            new ColumnNameData { ColumnText = "Reference", Label = "Item" },
            new ColumnNameData { ColumnText = "Reference No", Label = "Item" },
            new ColumnNameData { ColumnText = "Ref", Label = "Item" },
            new ColumnNameData { ColumnText = "Ref No", Label = "Item" },
            new ColumnNameData { ColumnText = "Product Ref", Label = "Item" },
            new ColumnNameData { ColumnText = "Line No", Label = "Item" },
            new ColumnNameData { ColumnText = "Product Line", Label = "Item" },
            new ColumnNameData { ColumnText = "Catalog Line", Label = "Item" },
            new ColumnNameData { ColumnText = "Batch No", Label = "Item" },
            new ColumnNameData { ColumnText = "Batch", Label = "Item" },
            new ColumnNameData { ColumnText = "Lot No", Label = "Item" },
            new ColumnNameData { ColumnText = "Lot Number", Label = "Item" },
            new ColumnNameData { ColumnText = "Lot", Label = "Item" },
            new ColumnNameData { ColumnText = "Label", Label = "Item" },
            new ColumnNameData { ColumnText = "Item Label", Label = "Item" },
            new ColumnNameData { ColumnText = "Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Product Label", Label = "Item" },
            new ColumnNameData { ColumnText = "Tag", Label = "Item" },
            new ColumnNameData { ColumnText = "Drug", Label = "Item" },
            new ColumnNameData { ColumnText = "Drugs", Label = "Item" },
            new ColumnNameData { ColumnText = "Medicine", Label = "Item" },
            new ColumnNameData { ColumnText = "Medicines", Label = "Item" },
            new ColumnNameData { ColumnText = "Medication", Label = "Item" },
            new ColumnNameData { ColumnText = "Medications", Label = "Item" },
            new ColumnNameData { ColumnText = "Med", Label = "Item" },
            new ColumnNameData { ColumnText = "Med Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Tablet", Label = "Item" },
            new ColumnNameData { ColumnText = "Tablets", Label = "Item" },
            new ColumnNameData { ColumnText = "Capsule", Label = "Item" },
            new ColumnNameData { ColumnText = "Capsules", Label = "Item" },
            new ColumnNameData { ColumnText = "Injection", Label = "Item" },
            new ColumnNameData { ColumnText = "Injections", Label = "Item" },
            new ColumnNameData { ColumnText = "Syrup", Label = "Item" },
            new ColumnNameData { ColumnText = "Syrups", Label = "Item" },
            new ColumnNameData { ColumnText = "Ointment", Label = "Item" },
            new ColumnNameData { ColumnText = "Ointments", Label = "Item" },
            new ColumnNameData { ColumnText = "Cream", Label = "Item" },
            new ColumnNameData { ColumnText = "Creams", Label = "Item" },
            new ColumnNameData { ColumnText = "Lotion", Label = "Item" },
            new ColumnNameData { ColumnText = "Lotions", Label = "Item" },
            new ColumnNameData { ColumnText = "Solution", Label = "Item" },
            new ColumnNameData { ColumnText = "Solutions", Label = "Item" },
            new ColumnNameData { ColumnText = "Suspension", Label = "Item" },
            new ColumnNameData { ColumnText = "Suspensions", Label = "Item" },
            new ColumnNameData { ColumnText = "Drops", Label = "Item" },
            new ColumnNameData { ColumnText = "Eye Drops", Label = "Item" },
            new ColumnNameData { ColumnText = "Ear Drops", Label = "Item" },
            new ColumnNameData { ColumnText = "Nasal Spray", Label = "Item" },
            new ColumnNameData { ColumnText = "Inhaler", Label = "Item" },
            new ColumnNameData { ColumnText = "Inhalers", Label = "Item" },
            new ColumnNameData { ColumnText = "Pill", Label = "Item" },
            new ColumnNameData { ColumnText = "Pills", Label = "Item" },
            new ColumnNameData { ColumnText = "Dosage Form", Label = "Item" },
            new ColumnNameData { ColumnText = "Generic Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Brand Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Trade Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Scientific Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Pharmaceutical Product", Label = "Item" },
            new ColumnNameData { ColumnText = "Pharma Product", Label = "Item" },
            new ColumnNameData { ColumnText = "Drug ID", Label = "Item" },
            new ColumnNameData { ColumnText = "Drug Name", Label = "Item" },
            new ColumnNameData { ColumnText = "Medication ID", Label = "Item" },
            new ColumnNameData { ColumnText = "Rx", Label = "Item" },
            new ColumnNameData { ColumnText = "Prescription Item", Label = "Item" },
            new ColumnNameData { ColumnText = "Non-Prescription Item", Label = "Item" },
            new ColumnNameData { ColumnText = "OTC", Label = "Item" },
            new ColumnNameData { ColumnText = "OTC Product", Label = "Item" },
            new ColumnNameData { ColumnText = "Pharmacy Item", Label = "Item" },
            new ColumnNameData { ColumnText = "Batch Number", Label = "Item" },
            new ColumnNameData { ColumnText = "Lot Number", Label = "Item" },
            new ColumnNameData { ColumnText = "Formulation", Label = "Item" },
            // -------- Extended Arabic Synonyms --------
             // Arabic
            new ColumnNameData { ColumnText = "الصنف", Label = "Item" },
            new ColumnNameData { ColumnText = "المنتج", Label = "Item" },
            new ColumnNameData { ColumnText = "اسم المنتج", Label = "Item" },
            new ColumnNameData { ColumnText = "المادة", Label = "Item" },
            new ColumnNameData { ColumnText = "البضاعة", Label = "Item" },
            new ColumnNameData { ColumnText = "رمز الصنف", Label = "Item" },
            new ColumnNameData { ColumnText = "رمز المنتج", Label = "Item" },
            new ColumnNameData { ColumnText = "السلعة", Label = "Item" },
            new ColumnNameData { ColumnText = "السلع", Label = "Item" },
            new ColumnNameData { ColumnText = "الخامة", Label = "Item" },
            new ColumnNameData { ColumnText = "الخامات", Label = "Item" },
            new ColumnNameData { ColumnText = "رمز المادة", Label = "Item" },
            new ColumnNameData { ColumnText = "مخزون", Label = "Item" },
            new ColumnNameData { ColumnText = "رمز مخزون", Label = "Item" },
            new ColumnNameData { ColumnText = "رمز البضاعة", Label = "Item" },
            new ColumnNameData { ColumnText = "معرف المنتج", Label = "Item" },
            new ColumnNameData { ColumnText = "معرف الصنف", Label = "Item" },
            new ColumnNameData { ColumnText = "الموديل", Label = "Item" },
            new ColumnNameData { ColumnText = "التسعيرة", Label = "Item" },
            new ColumnNameData { ColumnText = "الرمز", Label = "Item" },
            new ColumnNameData { ColumnText = "الرموز", Label = "Item" },
            new ColumnNameData { ColumnText = "التسمية", Label = "Item" },
            new ColumnNameData { ColumnText = "الوسم", Label = "Item" },
            new ColumnNameData { ColumnText = "العلامة", Label = "Item" },
            new ColumnNameData { ColumnText = "المكونات", Label = "Item" },
            new ColumnNameData { ColumnText = "المكون", Label = "Item" },
            new ColumnNameData { ColumnText = "خط المنتج", Label = "Item" },
            new ColumnNameData { ColumnText = "خط الصنف", Label = "Item" },
            new ColumnNameData { ColumnText = "الدفعة", Label = "Item" },
            new ColumnNameData { ColumnText = "الكمية المباعة", Label = "Item" },
            new ColumnNameData { ColumnText = "المعروض", Label = "Item" },
            new ColumnNameData { ColumnText = "دواء", Label = "Item" },
            new ColumnNameData { ColumnText = "ادوية", Label = "Item" },
            new ColumnNameData { ColumnText = "الدواء", Label = "Item" },
            new ColumnNameData { ColumnText = "عقار", Label = "Item" },
            new ColumnNameData { ColumnText = "العقاقير", Label = "Item" },
            new ColumnNameData { ColumnText = "الدواء الطبي", Label = "Item" },
            new ColumnNameData { ColumnText = "الادوية", Label = "Item" },
            new ColumnNameData { ColumnText = "علاج", Label = "Item" },
            new ColumnNameData { ColumnText = "الاسم العلمي", Label = "Item" },
            new ColumnNameData { ColumnText = "الاسم التجاري", Label = "Item" },
            new ColumnNameData { ColumnText = "اسم الدواء", Label = "Item" },
            new ColumnNameData { ColumnText = "رمز الدواء", Label = "Item" },
            new ColumnNameData { ColumnText = "الصيدلانيات", Label = "Item" },
            new ColumnNameData { ColumnText = "المستحضر", Label = "Item" },
            new ColumnNameData { ColumnText = "المستحضرات", Label = "Item" },
            new ColumnNameData { ColumnText = "شراب", Label = "Item" },
            new ColumnNameData { ColumnText = "كبسولة", Label = "Item" },
            new ColumnNameData { ColumnText = "كبسولات", Label = "Item" },
            new ColumnNameData { ColumnText = "قرص", Label = "Item" },
            new ColumnNameData { ColumnText = "اقراص", Label = "Item" },
            new ColumnNameData { ColumnText = "مرهم", Label = "Item" },
            new ColumnNameData { ColumnText = "مراهم", Label = "Item" },
            new ColumnNameData { ColumnText = "قطرة", Label = "Item" },
            new ColumnNameData { ColumnText = "قطرات", Label = "Item" },
            new ColumnNameData { ColumnText = "بخاخ", Label = "Item" },
            new ColumnNameData { ColumnText = "بخاخات", Label = "Item" },
            new ColumnNameData { ColumnText = "مستحضر صيدلي", Label = "Item" },
            new ColumnNameData { ColumnText = "مستحضرات صيدلية", Label = "Item" },
            new ColumnNameData { ColumnText = "الصيدلاني", Label = "Item" },
            new ColumnNameData { ColumnText = "المنتج الدوائي", Label = "Item" },
            new ColumnNameData { ColumnText = "المستحضر الدوائي", Label = "Item" },
            new ColumnNameData { ColumnText = "التصنيف الدوائي", Label = "Item" },
            new ColumnNameData { ColumnText = "المستحضر الطبي", Label = "Item" },
            new ColumnNameData { ColumnText = "العلاج", Label = "Item" },

            // -------- Common OCR / Misspellings --------
            new ColumnNameData { ColumnText = "Itm", Label = "Item" },
            new ColumnNameData { ColumnText = "Iteam", Label = "Item" },
            new ColumnNameData { ColumnText = "Itam", Label = "Item" },
            new ColumnNameData { ColumnText = "Prdct", Label = "Item" },
            new ColumnNameData { ColumnText = "Prodct", Label = "Item" },
            new ColumnNameData { ColumnText = "Bracode", Label = "Item" },
            new ColumnNameData { ColumnText = "Barcod", Label = "Item" },
            new ColumnNameData { ColumnText = "Skew", Label = "Item" },
            new ColumnNameData { ColumnText = "SkU", Label = "Item" },
            new ColumnNameData { ColumnText = "Matrl", Label = "Item" },
            new ColumnNameData { ColumnText = "Artcl", Label = "Item" },
            new ColumnNameData { ColumnText = "Goodz", Label = "Item" },
            new ColumnNameData { ColumnText = "Gooods", Label = "Item" },
            new ColumnNameData { ColumnText = "Produc", Label = "Item" },
            new ColumnNameData { ColumnText = "Prod Name", Label = "Item" },


            // ================= QUANTITY =================
            // English
            new ColumnNameData { ColumnText = "Quantity", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Qty", Label = "Quantity" },
            new ColumnNameData { ColumnText = "QTY", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Count", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Units", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Pieces", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Nos", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Amount", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Number of Items", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Pack Size", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Package", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Bottle", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Box", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Carton", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Strip", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Blister", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Vial", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Syringe", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Ampoule", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Capsule Count", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Tablet Count", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Dose Count", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Prescription Qty", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Refill Quantity", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Remaining Qty", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Stock Qty", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Available Units", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Supplied Quantity", Label = "Quantity" },
            new ColumnNameData { ColumnText = "Dispensed Qty", Label = "Quantity" },

            // Arabic
            new ColumnNameData { ColumnText = "الكمية", Label = "Quantity" },
            new ColumnNameData { ColumnText = "عدد", Label = "Quantity" },
            new ColumnNameData { ColumnText = "العدد", Label = "Quantity" },
            new ColumnNameData { ColumnText = "وحدات", Label = "Quantity" },
            new ColumnNameData { ColumnText = "قطع", Label = "Quantity" },
            new ColumnNameData { ColumnText = "علبة", Label = "Quantity" },
            new ColumnNameData { ColumnText = "علب", Label = "Quantity" },
            new ColumnNameData { ColumnText = "عبوة", Label = "Quantity" },
            new ColumnNameData { ColumnText = "عبوات", Label = "Quantity" },
            new ColumnNameData { ColumnText = "زجاجة", Label = "Quantity" },
            new ColumnNameData { ColumnText = "كرتونة", Label = "Quantity" },
            new ColumnNameData { ColumnText = "شريط", Label = "Quantity" },
            new ColumnNameData { ColumnText = "امبول", Label = "Quantity" },
            new ColumnNameData { ColumnText = "امبول", Label = "Quantity" },
            new ColumnNameData { ColumnText = "فيال", Label = "Quantity" },
            new ColumnNameData { ColumnText = "سرنجة", Label = "Quantity" },
            new ColumnNameData { ColumnText = "كبسولات", Label = "Quantity" },
            new ColumnNameData { ColumnText = "اقراص", Label = "Quantity" },
            new ColumnNameData { ColumnText = "جرعة", Label = "Quantity" },
            new ColumnNameData { ColumnText = "كمية الوصفة", Label = "Quantity" },
            new ColumnNameData { ColumnText = "كمية الصرف", Label = "Quantity" },
            new ColumnNameData { ColumnText = "كمية متاحة", Label = "Quantity" },
            new ColumnNameData { ColumnText = "رصيد متبقي", Label = "Quantity" },



            // ================= PRICE & TOTAL =================
            new ColumnNameData { ColumnText = "Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Unit Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Cost", Label = "Price" },
            new ColumnNameData { ColumnText = "Selling Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Net Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Base Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Retail Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Subtotal", Label = "Price" },
            new ColumnNameData { ColumnText = "Sub Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Grand Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Final Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Overall Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Balance", Label = "Price" },
            new ColumnNameData { ColumnText = "Amount Due", Label = "Price" },
            new ColumnNameData { ColumnText = "Total Amount", Label = "Price" },

            // -------- Extended English Synonyms --------
            new ColumnNameData { ColumnText = "Charge", Label = "Price" },
            new ColumnNameData { ColumnText = "Charges", Label = "Price" },
            new ColumnNameData { ColumnText = "Fee", Label = "Price" },
            new ColumnNameData { ColumnText = "Fees", Label = "Price" },
            new ColumnNameData { ColumnText = "Payment", Label = "Price" },
            new ColumnNameData { ColumnText = "Payments", Label = "Price" },
            new ColumnNameData { ColumnText = "Invoice Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Invoice Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Billing Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Bill Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Billed Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Due Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Due Balance", Label = "Price" },
            new ColumnNameData { ColumnText = "Line Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Row Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Amount Payable", Label = "Price" },
            new ColumnNameData { ColumnText = "Payable", Label = "Price" },
            new ColumnNameData { ColumnText = "Settlement", Label = "Price" },
            new ColumnNameData { ColumnText = "Gross Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Gross Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Taxable Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Amount Incl. Tax", Label = "Price" },
            new ColumnNameData { ColumnText = "Amount Excl. Tax", Label = "Price" },
            new ColumnNameData { ColumnText = "Bill Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Final Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Sale Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Unit Cost", Label = "Price" },
            new ColumnNameData { ColumnText = "Net Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Value", Label = "Price" },
            new ColumnNameData { ColumnText = "Total Value", Label = "Price" },
            new ColumnNameData { ColumnText = "Sum", Label = "Price" },
            new ColumnNameData { ColumnText = "Extended Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Ext. Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Extended Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Retail Amount", Label = "Price" },
            new ColumnNameData { ColumnText = "Cash Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Wholesale Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Market Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Current Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Listed Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Marked Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Catalog Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Tariff", Label = "Price" },
            new ColumnNameData { ColumnText = "Rate", Label = "Price" },
            new ColumnNameData { ColumnText = "Unit Rate", Label = "Price" },
            new ColumnNameData { ColumnText = "Chargeable", Label = "Price" },
            new ColumnNameData { ColumnText = "Settlement Amount", Label = "Price" },

            // -------- Arabic Synonyms --------
            new ColumnNameData { ColumnText = "السعر", Label = "Price" },
            new ColumnNameData { ColumnText = "سعر الوحدة", Label = "Price" },
            new ColumnNameData { ColumnText = "التكلفة", Label = "Price" },
            new ColumnNameData { ColumnText = "سعر البيع", Label = "Price" },
            new ColumnNameData { ColumnText = "سعر الشراء", Label = "Price" },
            new ColumnNameData { ColumnText = "سعر الجملة", Label = "Price" },
            new ColumnNameData { ColumnText = "سعر الاجمالي", Label = "Price" },
            new ColumnNameData { ColumnText = "السعر الصافي", Label = "Price" },
            new ColumnNameData { ColumnText = "سعر المستهلك", Label = "Price" },
            new ColumnNameData { ColumnText = "سعر السوق", Label = "Price" },
            new ColumnNameData { ColumnText = "المبلغ", Label = "Price" },
            new ColumnNameData { ColumnText = "المبلغ الكلي", Label = "Price" },
            new ColumnNameData { ColumnText = "المبلغ الاجمالي", Label = "Price" },
            new ColumnNameData { ColumnText = "الاجمالي", Label = "Price" },
            new ColumnNameData { ColumnText = "الاجمالي الكلي", Label = "Price" },
            new ColumnNameData { ColumnText = "الاجمالي النهائي", Label = "Price" },
            new ColumnNameData { ColumnText = "المجموع", Label = "Price" },
            new ColumnNameData { ColumnText = "الصافي", Label = "Price" },
            new ColumnNameData { ColumnText = "المبلغ المستحق", Label = "Price" },
            new ColumnNameData { ColumnText = "المبلغ المطلوب", Label = "Price" },
            new ColumnNameData { ColumnText = "المبلغ النهائي", Label = "Price" },
            new ColumnNameData { ColumnText = "الرصيد", Label = "Price" },
            new ColumnNameData { ColumnText = "رصيد نهائي", Label = "Price" },
            new ColumnNameData { ColumnText = "القيمة", Label = "Price" },
            new ColumnNameData { ColumnText = "القيمة الكلية", Label = "Price" },
            new ColumnNameData { ColumnText = "قيمة الصافي", Label = "Price" },
            new ColumnNameData { ColumnText = "قيمة البيع", Label = "Price" },
            new ColumnNameData { ColumnText = "قيمة الشراء", Label = "Price" },
            new ColumnNameData { ColumnText = "قيمة المبيعات", Label = "Price" },
            new ColumnNameData { ColumnText = "المدفوع", Label = "Price" },
            new ColumnNameData { ColumnText = "الدفع", Label = "Price" },
            new ColumnNameData { ColumnText = "المال", Label = "Price" },
            new ColumnNameData { ColumnText = "النقود", Label = "Price" },
            new ColumnNameData { ColumnText = "المتبقي", Label = "Price" },
            new ColumnNameData { ColumnText = "المديونية", Label = "Price" },
            new ColumnNameData { ColumnText = "المبلغ الاجمالي المطلوب", Label = "Price" },
            new ColumnNameData { ColumnText = "الحساب", Label = "Price" },

            // -------- OCR / Misspellings --------
            new ColumnNameData { ColumnText = "Prce", Label = "Price" },
            new ColumnNameData { ColumnText = "Preice", Label = "Price" },
            new ColumnNameData { ColumnText = "Prc", Label = "Price" },
            new ColumnNameData { ColumnText = "Pri", Label = "Price" },
            new ColumnNameData { ColumnText = "U.Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Unite Price", Label = "Price" },
            new ColumnNameData { ColumnText = "Totl", Label = "Price" },
            new ColumnNameData { ColumnText = "Tot", Label = "Price" },
            new ColumnNameData { ColumnText = "Ttal", Label = "Price" },
            new ColumnNameData { ColumnText = "Amnt", Label = "Price" },
            new ColumnNameData { ColumnText = "Amt", Label = "Price" },
            new ColumnNameData { ColumnText = "Bal", Label = "Price" },
            new ColumnNameData { ColumnText = "Blnce", Label = "Price" },
            new ColumnNameData { ColumnText = "Due Amt", Label = "Price" },
            new ColumnNameData { ColumnText = "Finl Total", Label = "Price" },
            new ColumnNameData { ColumnText = "Grnd Total", Label = "Price" },


            // ================= DISCOUNT1 =================
            new ColumnNameData { ColumnText = "Discount", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Disc1", Label = "Discount1" },
            new ColumnNameData { ColumnText = "D1", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Discount1", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Discount One", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Promo", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Offer", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Rebate", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Markdown", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Discount Ratio", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Discount %", Label = "Discount1" },
            new ColumnNameData { ColumnText = "Discount Percentage", Label = "Discount1" },
            // Arabic
            new ColumnNameData { ColumnText = "الخصم", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خصم1", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خصم اول", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خصم واحد", Label = "Discount1" },
            new ColumnNameData { ColumnText = "الخصم الاول", Label = "Discount1" },
            new ColumnNameData { ColumnText = "عرض", Label = "Discount1" },
            new ColumnNameData { ColumnText = "تخفيض", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خ1", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خ 1", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خ", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خ%", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خ١", Label = "Discount1" },
            new ColumnNameData { ColumnText = "نسبة خصم", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خصم %", Label = "Discount1" },
            new ColumnNameData { ColumnText = "خصومات", Label = "Discount1" },

            // ================= DISCOUNT2 =================
            new ColumnNameData { ColumnText = "Discount 2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "Disc2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "D2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "Discount2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "Discount Two", Label = "Discount2" },
            new ColumnNameData { ColumnText = "Extra Discount", Label = "Discount2" },
            new ColumnNameData { ColumnText = "Additional Discount", Label = "Discount2" },
            new ColumnNameData { ColumnText = "Discount Ratio 2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "Discount %2", Label = "Discount2" },
            // Arabic
            new ColumnNameData { ColumnText = "خصم 2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "خصم إضافي", Label = "Discount2" },
            new ColumnNameData { ColumnText = "تخفيض إضافي", Label = "Discount2" },
            new ColumnNameData { ColumnText = "الخصم الثاني", Label = "Discount2" },
            new ColumnNameData { ColumnText = "خصم ثاني", Label = "Discount2" },
            new ColumnNameData { ColumnText = "خ2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "خ 2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "خ٢", Label = "Discount2" },
            new ColumnNameData { ColumnText = "نسبة خصم 2", Label = "Discount2" },
            new ColumnNameData { ColumnText = "خصم %٢", Label = "Discount2" },
            new ColumnNameData { ColumnText = "خصومات 2", Label = "Discount2" },

            // ================= DISCOUNT3 =================
            new ColumnNameData { ColumnText = "Discount 3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "Disc3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "D3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "Discount3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "Discount Three", Label = "Discount3" },
            new ColumnNameData { ColumnText = "Special Discount", Label = "Discount3" },
            new ColumnNameData { ColumnText = "Final Discount", Label = "Discount3" },
            new ColumnNameData { ColumnText = "Discount Ratio 3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "Discount %3", Label = "Discount3" },
            // Arabic
            new ColumnNameData { ColumnText = "خصم 3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "خصم نهائي", Label = "Discount3" },
            new ColumnNameData { ColumnText = "خصم النهائي", Label = "Discount3" },
            new ColumnNameData { ColumnText = "تخفيض خاص", Label = "Discount3" },
            new ColumnNameData { ColumnText = "الخصم الثالث", Label = "Discount3" },
            new ColumnNameData { ColumnText = "خصم ثالث", Label = "Discount3" },
            new ColumnNameData { ColumnText = "خ3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "خ 3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "خ٣", Label = "Discount3" },
            new ColumnNameData { ColumnText = "نسبة خصم 3", Label = "Discount3" },
            new ColumnNameData { ColumnText = "خصم %٣", Label = "Discount3" },
            new ColumnNameData { ColumnText = "خصومات 3", Label = "Discount3" },

            };

    }
}
